apimServiceName: apim-wk-prod
namedValues:
 
  - name: mysecretvalue
    properties:
      displayName: mysecretvalue
      keyVault:
        secretIdentifier: https://waelskv.vault.azure.net/secrets/mysecretvalueprod
  - name: environment
    properties:
      displayName: environment
      value: "https://www.search2.com"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"
loggers:
    - name: apim-wk-insights
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/4833a5a2-133e-4bbc-9f54-86afc2f132bb/resourceGroups/
                   rg-apiops-prod/providers/microsoft.insights/components/apim-wk-prod-insights"
        credentials:
          instrumentationKey: "{{Logger-Credentials--63bcbaac217d200c94c65f22}}"
        isBuffered: true
diagnostics:
   - name: applicationinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/4833a5a2-133e-4bbc-9f54-86afc2f132bb/resourceGroups/rg-apiops-prod/providers/Microsoft.ApiManagement/service/apim-wk-prod/loggers/apim-wk-prod-insights"
